### PR TITLE
DRAFT: Remove arbitrary amplitude cutoffs

### PR DESCRIPTION
**Pull request by cmd8**

### CODE REVIEW

**Comment by cmd8** [comment]
It seems like there are several places where values below an arbitrary size are eliminated, which causes issues on badly-scaled (e.g. non-normalized) problems.

I have not done a thorough check to make sure all such instances are included in this PR. Additional input/feedback is very welcome.

**Comment by prj-** [comment]
Any chance that you provide a small example that exhibits this (previously bad) behavior?

**Comment by cmd8** [comment]
I can try to make one! I think it could pop up in many existing examples if we just scale the mesh down by a small constant factor (e.g. using `movemesh()`). I actually haven't solved my issue yet (hence the DRAFT), but it seems to be related to some area/amplitude threshold like this. There seem to be several places in the source where similar cutoffs are present.

**Comment by cmd8** [comment]
I thought I was close, but it seems this might take a little more work for me to fully understand what's going on... Will close for now and circle back later

**Pull request closed without merging**
